# -*- coding: utf-8 -*-
"""labwork5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LMK7JvndqvDikIhNlgobAl-HLifHONoh
"""

import sys
import numba
from numba import cuda
import numpy as np
from numba import vectorize
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from numpy import asarray


img = cv.imread("./example-orig.jpg")
im_resized = cv.resize(img, (224, 224), interpolation=cv.INTER_LINEAR)
plt.imshow(cv.cvtColor(im_resized, cv.COLOR_BGR2RGB))
plt.axis('off')
plt.show()

x_data = np.array(img)


imageWidth,imageHeight,c = x_data.shape

@cuda.jit
def rgb2gray(src, dst):
  tidx = cuda.threadIdx.x + cuda.blockIdx.x * cuda.blockDim.x
  tidy = cuda.threadIdx.y + cuda.blockIdx.y * cuda.blockDim.y
  g = np.uint8((src[tidx,tidy, 0] + src[tidx,tidy, 1] + src[tidx,tidy, 2]) / 3)
  dst[tidx,tidy, 0] = dst[tidx,tidy, 1] = dst[tidx,tidy, 2] = g


pixelCount = imageWidth * imageHeight
gridSize = (8, 8);
blockSize = (32, 32);

devSrc = cuda.to_device(x_data)
devDst = cuda.device_array((pixelCount, 3), np.uint8)
rgb2gray[gridSize, blockSize](devSrc, devDst)
hostDst = devDst.copy_to_host()