# -*- coding: utf-8 -*-
"""HPCSon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LyEM_RUx02LqLHQcf4GaFdCpVf01yWlq
"""

!apt-get install nvidia-cuda-toolkit
!pip3 install numba

!find / -iname 'libdevice'
!find / -iname 'libnvvm.so'

import os
os.environ['NUMBAPRO_LIBDEVICE'] = "/usr/local/cuda-11.2/nvvm/libdevice"
os.environ['NUMBAPRO_NVVM'] = "/usr/local/cuda-11.2/nvvm/lib64/libnvvm.so"

import numba
from numba import cuda

print(np.__version__)
print(numba.__version__)


cuda.gpus
cuda.current_context().get_memory_info()

"""# New Section

# New Section
"""